// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: config/v1/api.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropCond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: uri:"key"
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty" uri:"key"`
}

func (x *PropCond) Reset() {
	*x = PropCond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropCond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropCond) ProtoMessage() {}

func (x *PropCond) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropCond.ProtoReflect.Descriptor instead.
func (*PropCond) Descriptor() ([]byte, []int) {
	return file_config_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *PropCond) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Prop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Prop) Reset() {
	*x = Prop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prop) ProtoMessage() {}

func (x *Prop) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prop.ProtoReflect.Descriptor instead.
func (*Prop) Descriptor() ([]byte, []int) {
	return file_config_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *Prop) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_config_v1_api_proto protoreflect.FileDescriptor

var file_config_v1_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6e, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x1e, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x56, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x4c, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6e, 0x64, 0x1a, 0x13,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x70, 0x72,
	0x6f, 0x70, 0x2f, 0x7b, 0x6b, 0x65, 0x79, 0x7d, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x69, 0x61, 0x78, 0x30, 0x30, 0x2f, 0x73,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x7a, 0x65, 0x72, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_v1_api_proto_rawDescOnce sync.Once
	file_config_v1_api_proto_rawDescData = file_config_v1_api_proto_rawDesc
)

func file_config_v1_api_proto_rawDescGZIP() []byte {
	file_config_v1_api_proto_rawDescOnce.Do(func() {
		file_config_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_v1_api_proto_rawDescData)
	})
	return file_config_v1_api_proto_rawDescData
}

var file_config_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_v1_api_proto_goTypes = []interface{}{
	(*PropCond)(nil), // 0: api.config.v1.PropCond
	(*Prop)(nil),     // 1: api.config.v1.Prop
}
var file_config_v1_api_proto_depIdxs = []int32{
	0, // 0: api.config.v1.Config.GetProp:input_type -> api.config.v1.PropCond
	1, // 1: api.config.v1.Config.GetProp:output_type -> api.config.v1.Prop
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_v1_api_proto_init() }
func file_config_v1_api_proto_init() {
	if File_config_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropCond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_api_proto_goTypes,
		DependencyIndexes: file_config_v1_api_proto_depIdxs,
		MessageInfos:      file_config_v1_api_proto_msgTypes,
	}.Build()
	File_config_v1_api_proto = out.File
	file_config_v1_api_proto_rawDesc = nil
	file_config_v1_api_proto_goTypes = nil
	file_config_v1_api_proto_depIdxs = nil
}
