// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config/v1/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PropCond struct {
	// @gotags: form:"key" uri:"key"
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty" form:"key" uri:"key"`
	// @gotags: form:"prefix"
	Prefix               bool     `protobuf:"varint,2,opt,name=prefix,proto3" json:"prefix,omitempty" form:"prefix"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropCond) Reset()         { *m = PropCond{} }
func (m *PropCond) String() string { return proto.CompactTextString(m) }
func (*PropCond) ProtoMessage()    {}
func (*PropCond) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3153a2604995399, []int{0}
}
func (m *PropCond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropCond.Unmarshal(m, b)
}
func (m *PropCond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropCond.Marshal(b, m, deterministic)
}
func (m *PropCond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropCond.Merge(m, src)
}
func (m *PropCond) XXX_Size() int {
	return xxx_messageInfo_PropCond.Size(m)
}
func (m *PropCond) XXX_DiscardUnknown() {
	xxx_messageInfo_PropCond.DiscardUnknown(m)
}

var xxx_messageInfo_PropCond proto.InternalMessageInfo

func (m *PropCond) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PropCond) GetPrefix() bool {
	if m != nil {
		return m.Prefix
	}
	return false
}

type PropReply struct {
	// @gotags: json:"kvs"
	Kvs                  []*KvObj `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropReply) Reset()         { *m = PropReply{} }
func (m *PropReply) String() string { return proto.CompactTextString(m) }
func (*PropReply) ProtoMessage()    {}
func (*PropReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3153a2604995399, []int{1}
}
func (m *PropReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropReply.Unmarshal(m, b)
}
func (m *PropReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropReply.Marshal(b, m, deterministic)
}
func (m *PropReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropReply.Merge(m, src)
}
func (m *PropReply) XXX_Size() int {
	return xxx_messageInfo_PropReply.Size(m)
}
func (m *PropReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PropReply.DiscardUnknown(m)
}

var xxx_messageInfo_PropReply proto.InternalMessageInfo

func (m *PropReply) GetKvs() []*KvObj {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type KvObj struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KvObj) Reset()         { *m = KvObj{} }
func (m *KvObj) String() string { return proto.CompactTextString(m) }
func (*KvObj) ProtoMessage()    {}
func (*KvObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3153a2604995399, []int{2}
}
func (m *KvObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvObj.Unmarshal(m, b)
}
func (m *KvObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvObj.Marshal(b, m, deterministic)
}
func (m *KvObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvObj.Merge(m, src)
}
func (m *KvObj) XXX_Size() int {
	return xxx_messageInfo_KvObj.Size(m)
}
func (m *KvObj) XXX_DiscardUnknown() {
	xxx_messageInfo_KvObj.DiscardUnknown(m)
}

var xxx_messageInfo_KvObj proto.InternalMessageInfo

func (m *KvObj) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KvObj) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*PropCond)(nil), "api.config.v1.PropCond")
	proto.RegisterType((*PropReply)(nil), "api.config.v1.PropReply")
	proto.RegisterType((*KvObj)(nil), "api.config.v1.KvObj")
}

func init() { proto.RegisterFile("config/v1/api.proto", fileDescriptor_b3153a2604995399) }

var fileDescriptor_b3153a2604995399 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2f, 0x33, 0xd4, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x05, 0x31, 0x21, 0x12, 0x7a, 0x65, 0x86, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9,
	0x20, 0x05, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0xc5,
	0x4a, 0x26, 0x5c, 0x1c, 0x01, 0x45, 0xf9, 0x05, 0xce, 0xf9, 0x79, 0x29, 0x42, 0x02, 0x5c, 0xcc,
	0xd9, 0xa9, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x18, 0x17, 0x5b,
	0x41, 0x51, 0x6a, 0x5a, 0x66, 0x85, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x94, 0xa7, 0x64,
	0xcc, 0xc5, 0x09, 0xd2, 0x15, 0x94, 0x5a, 0x90, 0x53, 0x29, 0xa4, 0xc6, 0xc5, 0x9c, 0x5d, 0x56,
	0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa2, 0x87, 0x62, 0xbb, 0x9e, 0x77, 0x99, 0x7f,
	0x52, 0x56, 0x10, 0x48, 0x81, 0x92, 0x3e, 0x17, 0x2b, 0x98, 0x87, 0xc5, 0x1e, 0x11, 0x2e, 0xd6,
	0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0xb0, 0x35, 0x9c, 0x41, 0x10, 0x8e, 0x51, 0x34, 0x17, 0x9b, 0x33,
	0xd8, 0x20, 0xa1, 0x40, 0x2e, 0x76, 0xf7, 0xd4, 0x12, 0x90, 0x95, 0x42, 0xe2, 0x68, 0x16, 0xc0,
	0x5c, 0x2f, 0x25, 0x81, 0x45, 0x02, 0xec, 0x40, 0x25, 0xe1, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0xf1,
	0x0a, 0x71, 0xeb, 0x17, 0x14, 0xe5, 0x17, 0xe8, 0x57, 0x67, 0xa7, 0x56, 0xd6, 0x3a, 0x19, 0x45,
	0x19, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xe7, 0xa4, 0x66, 0x26,
	0x56, 0x18, 0x18, 0xe8, 0x17, 0x67, 0xe6, 0x16, 0xe4, 0xa4, 0xea, 0x56, 0xa5, 0x16, 0xe5, 0x83,
	0x03, 0x0c, 0x1e, 0xbe, 0xd6, 0x89, 0x05, 0x99, 0x49, 0x6c, 0xe0, 0x30, 0x33, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0x6f, 0xfd, 0xdb, 0x77, 0x01, 0x00, 0x00,
}
