// Code generated by github.com/leiax00/protoc-gen-gin. DO NOT EDIT.

package api

import (
	context "context"
	errors "errors"
	gin "github.com/gin-gonic/gin"
	metadata "google.golang.org/grpc/metadata"
)

// This is a compile-time assertion to ensure that this generated file is compatible
// with the leiax00/protoc-gen-gin package it is being compiled against.
// context.metadata.
//gin.errors.

type ConfigHttpServer interface {
	GetProp(context.Context, *PropCond) (*PropReply, error)

	SetUiConf(context.Context, *UIConfig) (*UIConfigReply, error)
}

type ConfigCtl struct {
	srv ConfigHttpServer
}

func RegisterConfigHttpServer(r gin.IRouter, srv ConfigHttpServer) {
	ctl := &ConfigCtl{srv}
	r.Handle("GET", "/config/v1/prop/:key", ctl._GetProp0)
	r.Handle("POST", "/config/v1/ui-conf", ctl._SetUiConf0)
}

func (ctl *ConfigCtl) _GetProp0(ctx *gin.Context) {
	var in PropCond

	if err := ctx.ShouldBindUri(&in); err != nil {
		ctl.paramsError(ctx, err)
		return
	}

	if err := ctx.ShouldBindQuery(&in); err != nil {
		ctl.paramsError(ctx, err)
		return
	}

	md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
	out, err := ctl.srv.GetProp(newCtx, &in)
	if err != nil {
		ctl.error(ctx, err)
		return
	}
	ctl.ok(ctx, out)
}

func (ctl *ConfigCtl) _SetUiConf0(ctx *gin.Context) {
	var in UIConfig

	if err := ctx.ShouldBindJSON(&in); err != nil {
		ctl.paramsError(ctx, err)
		return
	}

	md := metadata.New(nil)
	for k, v := range ctx.Request.Header {
		md.Set(k, v...)
	}
	newCtx := metadata.NewIncomingContext(ctx, md)
	out, err := ctl.srv.SetUiConf(newCtx, &in)
	if err != nil {
		ctl.error(ctx, err)
		return
	}
	ctl.ok(ctx, out)
}

func (ctl *ConfigCtl) response(ctx *gin.Context, httpCode, rpcCode int, msg any, data any) {
	ctx.JSON(httpCode, struct {
		Code int `json:"code"`
		Msg  any `json:"msg,omitempty"`
		Data any `json:"data,omitempty"`
	}{rpcCode, msg, data})
}

func (ctl *ConfigCtl) error(ctx *gin.Context, err error) {
	httpCode := 500
	rpcCode := -1
	reason := "UNKNOWN_ERR"
	msg := "UNKNOWN_ERR"

	if err == nil {
		msg += ", err is nil"
		ctl.response(ctx, httpCode, rpcCode, msg, nil)
		return
	}

	type iCode interface {
		GetCode() int32
		GetGrpcCode() int32
		GetReason() string
		GetMessage() string
	}

	var c iCode
	if errors.As(err, &c) {
		httpCode = int(c.GetCode())
		rpcCode = int(c.GetGrpcCode())
		reason = c.GetReason()
		msg = c.GetMessage()
	}

	_ = ctx.Error(err)

	ctl.response(ctx, httpCode, rpcCode, reason, nil)
}

func (ctl *ConfigCtl) paramsError(ctx *gin.Context, err error) {
	_ = ctx.Error(err)
	ctl.response(ctx, 400, 400, "PARAM_ERR", nil)
}

func (ctl *ConfigCtl) ok(ctx *gin.Context, data any) {
	ctl.response(ctx, 200, 0, nil, data)
}
