// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/leiax00/simple-zero/app/config/internal/conf"
	"github.com/leiax00/simple-zero/app/config/internal/server"
	"github.com/leiax00/simple-zero/pkg/logger"
)

// Injectors from wire.go:

func wireApp(config *conf.Config, loggerLogger *logger.Logger) *App {
	httpServer := server.NewHttpServer(loggerLogger)
	app := newApp(config, loggerLogger, httpServer)
	return app
}
