// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/conf/config.proto

package conf

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	logger "github.com/leiax00/simple-zero/pkg/logger"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	Log                  *logger.LogConf `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Server               *Server         `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_dddcc54f38d0136c, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLog() *logger.LogConf {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *Config) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

type Server struct {
	Http                 *Server_Http `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_dddcc54f38d0136c, []int{1}
}
func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetHttp() *Server_Http {
	if m != nil {
		return m.Http
	}
	return nil
}

type Server_Http struct {
	Network              string               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr                 string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout              *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Server_Http) Reset()         { *m = Server_Http{} }
func (m *Server_Http) String() string { return proto.CompactTextString(m) }
func (*Server_Http) ProtoMessage()    {}
func (*Server_Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_dddcc54f38d0136c, []int{1, 0}
}
func (m *Server_Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server_Http.Unmarshal(m, b)
}
func (m *Server_Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server_Http.Marshal(b, m, deterministic)
}
func (m *Server_Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server_Http.Merge(m, src)
}
func (m *Server_Http) XXX_Size() int {
	return xxx_messageInfo_Server_Http.Size(m)
}
func (m *Server_Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Server_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Server_Http proto.InternalMessageInfo

func (m *Server_Http) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Server_Http) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Server_Http) GetTimeout() *durationpb.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "sz.api.conf.Config")
	proto.RegisterType((*Server)(nil), "sz.api.conf.Server")
	proto.RegisterType((*Server_Http)(nil), "sz.api.conf.Server.Http")
}

func init() { proto.RegisterFile("internal/conf/config.proto", fileDescriptor_dddcc54f38d0136c) }

var fileDescriptor_dddcc54f38d0136c = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xf4, 0x30,
	0x10, 0x86, 0xe9, 0xb7, 0xa5, 0xcb, 0x66, 0x6f, 0xf9, 0x14, 0x6a, 0x0f, 0x22, 0x7b, 0x10, 0x41,
	0x4d, 0x16, 0xf7, 0xa8, 0x78, 0x50, 0x0f, 0x1e, 0x3c, 0xc5, 0x9b, 0x20, 0x92, 0x6e, 0xb3, 0xd9,
	0x60, 0xda, 0x09, 0xe9, 0x54, 0x65, 0xff, 0x8d, 0xff, 0x54, 0x92, 0xb6, 0xe0, 0x82, 0x97, 0x21,
	0x33, 0xf3, 0xcc, 0x3b, 0x79, 0x13, 0x52, 0x98, 0x06, 0x95, 0x6f, 0xa4, 0xe5, 0x6b, 0x68, 0x36,
	0x31, 0x18, 0xcd, 0x9c, 0x07, 0x04, 0x3a, 0x6f, 0x77, 0x4c, 0x3a, 0xc3, 0x42, 0xb1, 0x38, 0xb4,
	0xa0, 0xb5, 0xf2, 0xdc, 0x82, 0x7e, 0x0b, 0x85, 0x9e, 0x29, 0x8e, 0x35, 0x80, 0xb6, 0x8a, 0xc7,
	0xac, 0xec, 0x36, 0xbc, 0xea, 0xbc, 0x44, 0x03, 0x4d, 0xdf, 0x5f, 0xbc, 0x92, 0xec, 0x3e, 0x6a,
	0xd2, 0x53, 0x32, 0xb1, 0xa0, 0xf3, 0xe4, 0x24, 0x39, 0x9b, 0x5f, 0x1d, 0xb0, 0x5f, 0xda, 0xec,
	0x09, 0x74, 0x80, 0x44, 0x00, 0xe8, 0x39, 0xc9, 0x5a, 0xe5, 0x3f, 0x94, 0xcf, 0xff, 0x45, 0xf4,
	0xff, 0x1e, 0xfa, 0x1c, 0x5b, 0x62, 0x40, 0x16, 0xdf, 0x09, 0xc9, 0xfa, 0x12, 0xbd, 0x20, 0xe9,
	0x16, 0xd1, 0x0d, 0x0b, 0xf2, 0x3f, 0xa6, 0xd8, 0x23, 0xa2, 0x13, 0x91, 0x2a, 0x0c, 0x49, 0x43,
	0x46, 0x73, 0x32, 0x6d, 0x14, 0x7e, 0x82, 0x7f, 0x8f, 0x83, 0x33, 0x31, 0xa6, 0x94, 0x92, 0x54,
	0x56, 0x55, 0x7f, 0x8b, 0x99, 0x88, 0x67, 0xba, 0x22, 0x53, 0x34, 0xb5, 0x82, 0x0e, 0xf3, 0x49,
	0x5c, 0x73, 0xc4, 0x7a, 0xff, 0x6c, 0xf4, 0xcf, 0x1e, 0x06, 0xff, 0x62, 0x24, 0xef, 0x6e, 0x5f,
	0x6e, 0xb4, 0xc1, 0x6d, 0x57, 0xb2, 0x35, 0xd4, 0xdc, 0x2a, 0x23, 0xbf, 0x96, 0x4b, 0xde, 0x9a,
	0xda, 0x59, 0x75, 0xb9, 0x53, 0x1e, 0xb8, 0x74, 0x6e, 0x78, 0x79, 0xbe, 0xf7, 0x1d, 0xd7, 0x21,
	0x94, 0x59, 0xd4, 0x5e, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xd5, 0x81, 0x85, 0xab, 0x01,
	0x00, 0x00,
}
