env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - standard
parserOptions:
  ecmaVersion: 13
  parser: '@typescript-eslint/parser'
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
