app:
  title: 'Simple-Zero'
  version: 'v0.0.1'
  baseUrl: ''
  firstRun: '2021-11-15T17:00:00'
  copyright: 蜀ICP备2020031548号-1
  picCdn:
    base: https://cdn.jsdelivr.net/gh/leiax00/cdn-for-static
    #    base: https://cdn.leiax00.cn
    opts:
      pic: pic
  #  svg图片资源
  srcSvg: //at.alicdn.com/t/font_2015893_qyxz87dt3x.js

headers:
  - id: 'index'
    name: '首页'
    path: /index
  - id: 'novel'
    name: '小说'
    path: /novel

services:
  - name: novel-app
    prefix: /novel/
    domain: http://10.1.0.1:10001
