name: szui-main

on:
  workflow_dispatch: 
    inputs:
      appName:
        description: app名称
        required: true
        default: main
      appVersion:
        description: app版本
        required: true
        default: 1.0.2
      hubPlatforms:
        description: 镜像平台
        required: false
        default: linux/amd64

  push:
    # 每次 push tag 时进行构建，不需要每次 push 都构建。使用通配符匹配每次 tag 的提交，记得 tag 名一定要以 v 开头
    tags:
      - v*

jobs:
  build_image:
    # 如果需要在构建前进行测试的话需要取消下面的注释和上面对应的 test 动作的注释。
    # needs: test

    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      # 启动多平台构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: deploy/build/docker/Dockerfile_ui
          build-args: |
            RELATIVE_PATH=${{ github.event.inputs.appName }}
          # linux/amd64,linux/arm64/v8
          platforms: ${{ github.event.inputs.hubPlatforms }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/szui-${{ github.event.inputs.appName }}:${{ github.event.inputs.appVersion }}

  deploy:
    needs: build_image
    runs-on: ubuntu-latest

    steps:
      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /self/code/simple-zero/deploy/build/k8s
            git pull
            kubectl apply -f kube-szui-${{ github.event.inputs.appName }}.yaml --force